name: Publish to GHCR

on: 
  push:
    branches: [master]
    # Publish semver tags as releases. 
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [master]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  test:
    name: Run tests
    uses: rubenflinterman-com/noteshare.space/.github/workflows/test.yaml@master
  publish:
    name: Publish
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        env:
          REGISTRY: ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CI_GHCR_PAT }}

      - name: Extract metadata for Docker GHCR
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrate
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend

      - name: Build and push Docker image for migrate
        uses: docker/build-push-action@v5
        with:
          context: ./server/prisma
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/migrate:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v5
        with:
          context: ./webapp
          file: Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          labels: ${{ steps.meta.outputs.labels }}
